language: node_js
deploy:
  api_key:
    secure: oeL0l1fWLkxZdPHOOhtN6U8cNsp/rv8YiDp3BAciiZ6LIcC0qv9ZVd6FhZzFuEZnsoClMkIfAOrtEoqMtjJLKDcxg8Kql6JvnYSRpKKn+mEqIDdhjZ11gkNjdJ3GGt0D4pILCX5KfYr6qU90EVYlxJO8OmC9ADYEQhr0lBdISCg=
  provider: npm
  email: john@mclear.co.uk
